There is still something wrong, if you click resetBtn before click p1Btn and p2Btn which will call scoreAdder, then there will be error such as Uncaught TypeError: scoreAdder.scoreReset is not a function, that is because scoreAdder.scoreReset does not exist until you execute scoreAdder, trying to find a way out!